///////////////////////////////////////////////////////////
//  FavoritesDatabase.cs
//  Implementation of the Class FavoritesDatabase
//  Generated by Enterprise Architect
//  Created on:      10-Jun-2021 4:00:52 PM
//  Original author: beltran-gonzalezj
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Mellow_Music_Player {
	public class FavoritesDatabase : songList {

		private List<Song> favorites;

		public FavoritesDatabase(){

		}

		~FavoritesDatabase(){

		}

		/// 
		/// <param name="song"></param>
		public void addSong(Song song){

		}

		/// 
		/// <param name="song"></param>
		public void removeSong(Song song){

		}

		public List<Song> shuffle()
        {

			return null;

        }

	}//end FavoritesDatabase

}//end namespace uml