///////////////////////////////////////////////////////////
//  Playlist.cs
//  Implementation of the Class Playlist
//  Generated by Enterprise Architect
//  Created on:      10-Jun-2021 4:00:55 PM
//  Original author: beltran-gonzalezj
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Mellow_Music_Player {
	public class Playlist : songList {

		private string name;
		private List<Song> songs;

		public Playlist(){

		}

		~Playlist(){

		}

		/// 
		/// <param name="song"></param>
		public void addSong(Song song){

		}

		/// 
		/// <param name="song"></param>
		public void removeSong(Song song){

		}

		public List<Song> shuffle()
        {

			return null;

        }

	}//end Playlist

}//end namespace uml