///////////////////////////////////////////////////////////
//  Playlist.cs
//  Implementation of the Class Playlist
//  Generated by Enterprise Architect
//  Created on:      10-Jun-2021 4:00:55 PM
//  Original author: beltran-gonzalezj
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Mellow_Music_Player {
	public class Playlist : songList {

		public string name { get; set; }
		private List<Song> songs;

		public Playlist(){

			songs = new List<Song>();

		}

		~Playlist(){

		}

		/// 
		/// <param name="song"></param>
		public void addSong(Song song){

			songs.Add(song);

		}

		/// 
		/// <param name="song"></param>
		public void removeSong(Song song){

			songs.Remove(song);

		}

		public List<Song> shuffle()
        {

			return null;

        }

		public List<Song> getSongs()
        {

			return songs;

        }

        public override string ToString()
        {
			return name;
        }

    }//end Playlist

}//end namespace uml