///////////////////////////////////////////////////////////
//  PlaylistDatabase.cs
//  Implementation of the Class PlaylistDatabase
//  Generated by Enterprise Architect
//  Created on:      10-Jun-2021 4:00:56 PM
//  Original author: beltran-gonzalezj
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Mellow_Music_Player {
	public class PlaylistDatabase {

		private List<Playlist> playlists;

		public PlaylistDatabase(){

		}

		~PlaylistDatabase(){

		}

		/// 
		/// <param name="playlist"></param>
		public void addPlaylist(Playlist playlist){

		}

		/// 
		/// <param name="playlist"></param>
		public void removePlaylist(Playlist playlist){

		}

	}//end PlaylistDatabase

}//end namespace uml