///////////////////////////////////////////////////////////
//  RecentlyPlayedDatabase.cs
//  Implementation of the Class RecentlyPlayedDatabase
//  Generated by Enterprise Architect
//  Created on:      10-Jun-2021 4:00:57 PM
//  Original author: beltran-gonzalezj
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Mellow_Music_Player {
	public class RecentlyPlayedDatabase : songList {

		private List<Song> recentlyPlayed;

		public RecentlyPlayedDatabase(){

		}

		~RecentlyPlayedDatabase(){

		}

		/// 
		/// <param name="song"></param>
		public void addSong(Song song){

		}

		/// 
		/// <param name="song"></param>
		public void removeSong(Song song){

		}

		public List<Song> shuffle()
        {

			return null;

        }

	}//end RecentlyPlayedDatabase

}//end namespace uml