///////////////////////////////////////////////////////////
//  SongDatabase.cs
//  Implementation of the Class SongDatabase
//  Generated by Enterprise Architect
//  Created on:      10-Jun-2021 4:00:59 PM
//  Original author: beltran-gonzalezj
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Collections;

namespace Mellow_Music_Player {
	public class SongDatabase : songList {

		private ArrayList songs;

		public SongDatabase(){
			songs = new ArrayList();
		}

		/// 
		/// <param name="song"></param>
		public void addSong(Song song){
			songs.Add(song);
			IComparer comparer = new songList.AlphabetSorter();
		}

		/// 
		/// <param name="song"></param>
		public void removeSong(Song song){
			
		}

		public void sortList()
        {


        }

	}//end SongDatabase

}//end namespace uml