///////////////////////////////////////////////////////////
//  Song.cs
//  Implementation of the Class Song
//  Generated by Enterprise Architect
//  Created on:      10-Jun-2021 4:00:58 PM
//  Original author: beltran-gonzalezj
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Mellow_Music_Player {
	public class Song {

		public string album { get; set; }
		public string albumCover { get; set; }
		public string artist { get; set; }
		public string genre { get; set; }
		public string songFilepath { get; set; }
		public string songName { get; set; }
		public int year { get; set; }

		public Song(string songFilepath, string songName){


			this.songFilepath = songFilepath;
			this.songName = songName;

		}

        public override string ToString()
        {
            return songName;
        }

    }//end Song

}//end namespace uml