///////////////////////////////////////////////////////////
//  Song.cs
//  Implementation of the Class Song
//  Generated by Enterprise Architect
//  Created on:      10-Jun-2021 4:00:58 PM
//  Original author: beltran-gonzalezj
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Mellow_Music_Player {
	public class Song {

		private string album;
		private string albumCover;
		private string artist;
		private string genre;
		private string songFilepath;
		private string songName;
		private int year;

		public Song(){

		}

		~Song(){

		}

	}//end Song

}//end namespace uml