///////////////////////////////////////////////////////////
//  songList.cs
//  Implementation of the Interface songList
//  Generated by Enterprise Architect
//  Created on:      10-Jun-2021 4:01:01 PM
//  Original author: beltran-gonzalezj
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Collections;

namespace Mellow_Music_Player {
	public interface songList  {

        /// 
        /// <param name="song"></param>
        void addSong(Song song);

		/// 
		/// <param name="song"></param>
		void removeSong(Song song);
	}//end songList

}//end namespace uml