///////////////////////////////////////////////////////////
//  SongDatabase.cs
//  Implementation of the Class SongDatabase
//  Generated by Enterprise Architect
//  Created on:      10-Jun-2021 4:00:59 PM
//  Original author: beltran-gonzalezj
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Collections;

namespace Mellow_Music_Player {
	public class SongDatabase : songList {
		
		private List<Song> songs;

		public SongDatabase(){
			songs = new List<Song>();
		}

		/// 
		/// <param name="song"></param>
		public void addSong(Song song){
			songs.Add(song);
			IComparer<Song> comparer = new AlphabetSorter();
			songs.Sort(comparer);
		}

		/// 
		/// <param name="song"></param>
		public void removeSong(Song song){
			
		}

		public List<Song> getSongs()
        {

			return songs;

        }

		public void sortList()
        {


        }

		public List<Song> shuffle()
        {

			Random random = new Random();

			int databaseSize = songs.Count;
			List<Song> shuffledList = new List<Song>(songs);

			while(databaseSize > 1)
            {

				databaseSize--;

				int randomIndex = random.Next(databaseSize + 1);

				Song song = shuffledList[randomIndex];
				shuffledList[randomIndex] = shuffledList[databaseSize];
				shuffledList[databaseSize] = song;

            }

			return shuffledList;

        }



	}//end SongDatabase

}//end namespace uml